/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.veterinaria.GUI;

/**
 *
 * @author INSTRUCTOR
 */
public class PanelCardmedico extends javax.swing.JPanel {

    /**
     * Creates new form PanelTarActividad
     */
    public PanelCardmedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etq_nombre_mascota = new javax.swing.JLabel();
        etq_fecha = new javax.swing.JLabel();
        etq_descripcion = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        campo_actividad = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etq_nombre_mascota.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etq_nombre_mascota.setText("Mascota:");
        add(etq_nombre_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        etq_fecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etq_fecha.setText("Fecha:");
        add(etq_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        etq_descripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etq_descripcion.setText("Descripción:");
        add(etq_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        javax.swing.GroupLayout campo_actividadLayout = new javax.swing.GroupLayout(campo_actividad);
        campo_actividad.setLayout(campo_actividadLayout);
        campo_actividadLayout.setHorizontalGroup(
            campo_actividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        campo_actividadLayout.setVerticalGroup(
            campo_actividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(campo_actividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JPanel campo_actividad;
    private javax.swing.JLabel etq_descripcion;
    private javax.swing.JLabel etq_fecha;
    private javax.swing.JLabel etq_nombre_mascota;
    // End of variables declaration//GEN-END:variables
}
